### ISSUE TITLE
[BUG] - N/A with unraid 6.11

### ISSUE THREAD

**Issue by martabal** [b3rs3rk/gpustat-unraid#44]
**Describe the bug**

**Expected behavior**
Expect some values, but GPU Statistics prompts N/A with intel integrated graphics.

**Screenshots**
![image](https://user-images.githubusercontent.com/74269598/193453391-489af17c-f2c2-4bd3-bece-9a73dbc1d2bf.png)

**Client:**
 - OS: Windows 11
 - Browser: Firefox
 - Version: 105.0.1

**Server:**
 - Device: Physical Server
 - OS Version: UnRAID v6.11
 - GPU: Intel UHD 630 (Intel i5 9600k)

**Additional context**
Works perfectly when I restore Unraid 6.10.3. Issue discussed in [Unraid forums](https://forums.unraid.net/topic/89453-plugin-gpu-statistics/page/25)

**Comment by realizelol** [comment]
Hi,

please consider to remove the plus here in [Line#51](https://github.com/b3rs3rk/gpustat-unraid/blob/master/src/gpustat/usr/local/emhttp/plugins/gpustat/gpustatus.php#L51) otherwise it will break AMD APUs (also: AMD GPUs ?).

I am actually using a AMD Ryzen 7 4800U APU which will work again after replacing the line by:
`$gpustat_data = (new AMD($gpustat_cfg))->getInventory();`

I am not that confirm with php but wouldn't that add the AMD part to the newly added INTEL array [Merge#45](https://github.com/b3rs3rk/gpustat-unraid/pull/45)?

<br>

best regards

realizelol

<ins>Specs:</ins>
OS: macOS 12.6.1
Browser: Firefox v107.0
Device: Physical Server
OS Version: UnRAID v6.11.5
GPU: AMD Radeon RX Vega 8 (Renoir)   [AMD Ryzen 7 4800U - Zen2]

**Comment by b3rs3rk** [comment]
@realizelol Can you create a separate issue for this and not piggyback off this one?  What you are doing will break both Nvidia and Intel.  This is a separate issue that I need to track and diagnose (with your help) as I don't know of anyone having the same issue.

**Comment by b3rs3rk** [comment]
@martabal After the latest plugin update (Dated 2022-11-29) has your issue been resolved?

**Comment by martabal** [comment]
Yep, completely resolved, thank you !

**Comment by realizelol** [comment]
> @realizelol Can you create a separate issue for this and not piggyback off this one? What you are doing will break both Nvidia and Intel. This is a separate issue that I need to track and diagnose (with your help) as I don't know of anyone having the same issue.

Thanks a lot, next time I'll do so. My Problem is solved with the "nvidia"-fix ([PR#46](https://github.com/b3rs3rk/gpustat-unraid/pull/46)), so I won't open a new ticket at this time.

best regards
realizelol
